-- purely generated by Claude Opus 4.5

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE STD.TEXTIO.ALL;
USE IEEE.STD_LOGIC_TEXTIO.ALL;

ENTITY ball_bouncer_tb IS
END ball_bouncer_tb;

ARCHITECTURE Behavioral OF ball_bouncer_tb IS
    SIGNAL clk : STD_LOGIC := '0';
    SIGNAL rst : STD_LOGIC := '1';
    SIGNAL arena : STD_LOGIC_VECTOR(1023 DOWNTO 0);

    CONSTANT clk_period : TIME := 1 ns;

    -- Frame counter for controlling display rate
    SIGNAL frame_count : INTEGER := 0;

BEGIN
    uut : ENTITY work.ball_bouncer
        GENERIC MAP(
            ARENA_X => 32,
            ARENA_Y => 32,
            BALL_INIT_X => 10,
            BALL_INIT_Y => 0,
            BALL_SIZE => 3
        )
        PORT MAP(
            clk => clk,
            clk_en => '1',
            rst => rst,
            arena => arena
        );

    -- Clock generation
    clk_process : PROCESS
    BEGIN
        clk <= '0';
        WAIT FOR clk_period/2;
        clk <= '1';
        WAIT FOR clk_period/2;
    END PROCESS;

    -- Stimulus
    stim_proc : PROCESS
    BEGIN
        rst <= '1';
        WAIT FOR clk_period * 2;
        rst <= '0';

        -- Run for many cycles to see bouncing
        WAIT FOR clk_period * 200;

        REPORT "Simulation complete!";
        WAIT;
    END PROCESS;

    -- Display process with ASCII visualization
    display_proc : PROCESS (clk)
        VARIABLE l : line;
        VARIABLE pixel : STD_LOGIC;
        VARIABLE char : CHARACTER;
    BEGIN
        IF rising_edge(clk) AND rst = '0' THEN
            frame_count <= frame_count + 1;

            -- Display every frame (or adjust to display less frequently)
            IF true THEN -- Change to (frame_count mod 5 = 0) to display every 5th frame

                -- Clear screen sequence (works in most simulators)
                write(l, LF);
                write(l, STRING'("========================================"));
                write(l, LF);
                write(l, STRING'("Frame: "));
                write(l, frame_count);
                write(l, LF);
                write(l, STRING'("========================================"));
                writeline(output, l);

                -- Top border
                write(l, STRING'("+"));
                FOR x IN 0 TO 31 LOOP
                    write(l, STRING'("-"));
                END LOOP;
                write(l, STRING'("+"));
                writeline(output, l);

                -- Display each row
                FOR y IN 0 TO 31 LOOP
                    write(l, STRING'("|")); -- Left border

                    FOR x IN 0 TO 31 LOOP
                        -- Extract pixel from flattened array
                        pixel := arena(y * 32 + x);

                        IF pixel = '1' THEN
                            char := '#'; -- Ball pixel
                        ELSE
                            char := ' '; -- Empty space
                        END IF;

                        write(l, char);
                    END LOOP;

                    write(l, STRING'("|")); -- Right border
                    writeline(output, l);
                END LOOP;

                -- Bottom border
                write(l, STRING'("+"));
                FOR x IN 0 TO 31 LOOP
                    write(l, STRING'("-"));
                END LOOP;
                write(l, STRING'("+"));
                writeline(output, l);

                -- Extra spacing
                write(l, LF);
                writeline(output, l);
            END IF;
        END IF;
    END PROCESS;

END Behavioral;